name: groovin_material_icons_testapp
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  groovin_material_icons:
    path: ..
  cupertino_icons: ^0.1.2
  draggable_scrollbar: ^0.0.4
  url_launcher: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true